### ISSUE TITLE
Validate install instructions in the readme

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/python-zbMathRest2Oai#10]
https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/blob/70016cdd9cefcb036772ab8669b6cfbe03084592/README.md?plain=1#L7

This does not work for me. I see
```
ERROR: requirements.txt is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

**Comment by Mazztok45** [comment]
The requirements.txt and the README.md files have been updated thanks to the library freeze with:

`pip3 freeze > requirements.txt`

**Comment by physikerwelt** [comment]
This is not the practice at zbMATH Open. One should use . and specify the dependencies in the project.toml file. Take a look at the internal development guidelines.

**Comment by Mazztok45** [comment]
This commit clarifies the instructions to install the repo with the right command line :

**https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/commit/48b8628290347ef188b724dce96ae03f212130eb**
