### ISSUE TITLE
Create directory structure

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/python-zbMathRest2Oai#2]
For example:
```
.gitignore
requirements.txt
README.md
setup.cfg
setup.py
MANIFEST.in
src/  # all the package code goes inside here
  package1/
    __init__.py
    mod1.py
    mod2.py
  package2/
    __init__.py
    mod1.py
tests/
  test_package1.py
  test_package2.py

**Comment by physikerwelt** [comment]
This is close to being done. Maybe adding a codemeta JSON file would be an idea. Thereafter I would suggest checking with someone from the development team if the directory structure is ok.

**Comment by Mazztok45** [comment]
I just generated and added a codemeta.json file with the help of https://codemeta.github.io/codemeta-generator/. 
I will update this file once the project is achieved, at least for the beta release (specifying the version, a contextual SWHID, and possibly other details).
I look forward to improving the directory structure and reviewing it with a development team member.

**Comment by physikerwelt** [comment]
reopen if required please
