### ISSUE TITLE
XSLT transformation for software metadata

### ISSUE THREAD

**Issue by Mazztok45** [MaRDI4NFDI/python-zbMathRest2Oai#22]
**Describe the issue**
This issue aims to specify the target XML format we need to reach for the software metadata.

**Comment by Mazztok45** [comment]
Now the following request on https://oai.portal.mardi4nfdi.de/oai/OAIHandler:

identifier:2 
metadataPrefix:zbmath_rest_api

We get:

`<root>
  <result>
    <articles_count>102</articles_count>
    <authors>Li, X.S., Demmel, J.W.</authors>
    <classification>35</classification>
    <classification>65</classification>
    <classification>68</classification>
    <classification>74</classification>
    <classification>76</classification>
    <classification>05</classification>
    <classification>15</classification>
    <classification>60</classification>
    <classification>78</classification>
    <classification>80</classification>
    <classification>81</classification>
    <classification>82</classification>
    <classification>85</classification>
    <classification>86</classification>
    <classification>90</classification>
    <classification>92</classification>
    <dependencies></dependencies>
    <description>zbMATH Open Web Interface contents unavailable due to conflicting licenses.</description>
    <homepage>http://crd-legacy.lbl.gov/~xiaoye/SuperLU/</homepage>
    <id>2</id>
    <keywords>orms</keywords>
    <license_terms></license_terms>
    <name>SuperLU-DIST</name>
    <operating_systems></operating_systems>
    <orms_id>265</orms_id>
    <programming_languages></programming_languages>
    <related_software>
      <id>4013</id>
      <name>MUMPS</name>
    </related_software>
    <related_software>
      <id>4012</id>
      <name>PETSc</name>
    </related_software>
    <related_software>
      <id>930</id>
      <name>SuperLU</name>
    </related_software>
    <related_software>
      <id>4629</id>
      <name>SparseMatrix</name>
    </related_software>
    <related_software>
      <id>503</id>
      <name>LAPACK</name>
    </related_software>
    <related_software>
      <id>679</id>
      <name>PARDISO</name>
    </related_software>
    <related_software>
      <id>426</id>
      <name>hypre</name>
    </related_software>
    <related_software>
      <id>989</id>
      <name>UMFPACK</name>
    </related_software>
    <related_software>
      <id>4089</id>
      <name>METIS</name>
    </related_software>
    <related_software>
      <id>4028</id>
      <name>Trilinos</name>
    </related_software>
    <related_software>
      <id>830</id>
      <name>ScaLAPACK</name>
    </related_software>
    <related_software>
      <id>4827</id>
      <name>mctoolbox</name>
    </related_software>
    <related_software>
      <id>6749</id>
      <name>WSMP</name>
    </related_software>
    <related_software>
      <id>3216</id>
      <name>BLAS</name>
    </related_software>
    <related_software>
      <id>418</id>
      <name>HSL</name>
    </related_software>
    <related_software>
      <id>8067</id>
      <name>ML</name>
    </related_software>
    <related_software>
      <id>2780</id>
      <name>SPIKE</name>
    </related_software>
    <related_software>
      <id>6496</id>
      <name>MPI</name>
    </related_software>
    <related_software>
      <id>9043</id>
      <name>MFEM</name>
    </related_software>
    <related_software>
      <id>17483</id>
      <name>STRUMPACK</name>
    </related_software>
    <source_code></source_code>
    <standard_articles>
      <authors></authors>
      <id>2187846</id>
      <source>zbMATH Open Web Interface contents unavailable due to conflicting licenses.</source>
      <title>zbMATH Open Web Interface contents unavailable due to conflicting licenses.</title>
      <year>2003</year>
    </standard_articles>
    <zbmath_url>https://zbmath.org/software/2</zbmath_url>
  </result>
  <status>
    <execution>successful request</execution>
    <execution_bool>True</execution_bool>
    <internal_code>ok</internal_code>
    <query_execution_time_in_seconds>0.07225203514099121</query_execution_time_in_seconds>
    <status_code>200</status_code>
    <time_stamp>2024-02-09 12:49:18.259135</time_stamp>
  </status>
</root>`

**Comment by Mazztok45** [comment]
The Force 11 Software Citation Principles mapping helps with selecting the appropriate fields:

https://datacite-metadata-schema.readthedocs.io/en/4.5/mappings/force11-software-citation/

**Comment by Mazztok45** [comment]
Specific problem: Authors are concatenated in the same string; see:

` <creators>Li, X.S., Demmel, J.W.</creators>`

**Comment by physikerwelt** [comment]
> Specific problem: Authors are concatenated in the same string; see:
> 
> ` <creators>Li, X.S., Demmel, J.W.</creators>`

This is a problem to be solved upstream.

**Comment by physikerwelt** [comment]
orms can be exanded to https://orms.mfo.de/project@terms=&id=265.html

**Comment by Mazztok45** [comment]
> orms can be exanded to https://orms.mfo.de/project@terms=&id=265.html

The commit https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/commit/93f586001b09025b315bbebdfa10b327fdf3da6a adds the URL to ORMS.

**Comment by physikerwelt** [comment]
I think we can add a test and close the issue, ok?

**Comment by physikerwelt** [comment]
If you need help, more details are needed.

**Comment by Mazztok45** [comment]
I think I finally got the problem. 

In our plain.xml file, we have this ORMS id:

`<orms_id>265</orms_id>`

We concatenate it with these lines in the xslt file, I added the `&amp;` such the hyperlink displayed in the XML file works.

`<relatedIdentifier relationType="IsDescribedBy">
        <xsl:value-of disable-output-escaping="yes" select="concat('https://orms.mfo.de/project@terms=', '&amp;', 'id=' , root/result/orms_id, '.html')"/>
    </relatedIdentifier>`

 And it works. 
`<relatedIdentifier relationType="IsDescribedBy">https://orms.mfo.de/project@terms=&id=265.html</relatedIdentifier>`

However, this XML file is now invalid. As it should be `&` and not `&amp;`. But if we keep the `&`, then the link does not work.

So for now, I keep leaving the `&amp;` in the XSLT such that it displays `&`  and the hyperlink works. Even if the XML file seems invalid.

**Comment by physikerwelt** [comment]
This does not seem to be correct, in for articles, there is a specificity setting that determines the output format and to my understanding there should not be any & in [xml](https://www.w3.org/TR/xml/#syntax)...

https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/blob/99069189592c24d1ef5040dc3c01953420bc0a3e/xslt/articles/xslt-article-transformation.xslt#L10

Thus you need to generate &amp; in the final XML document

**Comment by physikerwelt** [comment]
Apart from that, just delete the empty parameter from the url and use

https://orms.mfo.de/project@id=265.html
