### ISSUE TITLE
Get all software

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/python-zbMathRest2Oai#29]
**Describe the issue**
Currently, a csv file is processed, however, this should be done for all software. Please coordinate with Marcel, to adjust the structured search for sofware so that it is possible to scan for an id range.

**Comment by physikerwelt** [comment]
From our meeting notes

Send requests

1) https://api.zbmath.org/v1/software/_search?search_string=si%3A0-100&page=0&results_per_page=100
2) https://api.zbmath.org/v1/software/_search?search_string=si%3A100-200&page=0&results_per_page=100

**Comment by physikerwelt** [comment]
This issue is from Feb 9th. Please focus on that with the highest priority.

**Comment by Mazztok45** [comment]
My apologies, this commit has fixed this issue: 

https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/commit/2a148a9c4d129cf042af2e77dea0d6c0034a6b82

We used the endpoint of the zbMATH Open API to get all the software we needed.
