### ISSUE TITLE
Setting new prefixes identifiers for both articles and software sent to the oai.portal.mardi4nfdi.de service

### ISSUE THREAD

**Issue by Mazztok45** [MaRDI4NFDI/python-zbMathRest2Oai#30]
**Describe the issue**
Identifiers do not have their own prefix, resulting in confusion between if an entity is an article or a software and causing overwriting of software over article document, either for the opposite. 
Creating new prefix for both entities should fix the situation.

**Comment by physikerwelt** [comment]
With the help of our colleague from Karlsruhe, I just found a problem with the deployment, which I fixed now.

**Comment by physikerwelt** [comment]
See for example https://oai.portal.mardi4nfdi.de/oai/OAIHandler?verb=GetRecord&metadataPrefix=zbmath_rest_api&identifier=prefix6383667
