### ISSUE TITLE
Getting the maximum value of indexes to have the workflow working optimally

### ISSUE THREAD

**Issue by Mazztok45** [MaRDI4NFDI/python-zbMathRest2Oai#31]
**Describe the issue**
We trigger the sending of entities between the REST API service and the OAI-PMH server on the MaRDI infrastructure.
This workflow processes with batches and can be interrupted due to time exceeding the rate limit for a request.
It is necessary to know the latest values for identifiers for articles and software and for REST API and OAI services to have an efficient workflow once we relaunch it.

**Comment by physikerwelt** [comment]
you can use the sickle client to send requests to the oai pmh api

**Comment by physikerwelt** [comment]
use the feature of marcel

**Comment by Mazztok45** [comment]
These two commits fix this issue:

https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/commit/0c4864ec97369002533e08d38bcad2a7731e6009#diff-90135a57cf730746e36fad0d8377d9e11a094e205fdd6b7e46fb56dd2800cfc2R6

https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/commit/2a148a9c4d129cf042af2e77dea0d6c0034a6b82#diff-480abe0ba2190472d14904646207eee3bc92d0e2017cb4a7a8daceac04dfd3bdR7
