### ISSUE TITLE
Add tests for XSLT files

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/python-zbMathRest2Oai#32]
see
https://stackoverflow.com/a/16699042/9215209

Apply xslt transform to document and compare with the expected result as done in https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/blob/c053cf6fb304ad130f866defa851051e4c4bd41c/test/test_oai_preview.py

**Comment by Mazztok45** [comment]
The last commit https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/commit/9173affd74e0224b01d9212a74c6d2c3b78f6498 comes with zero error now. Some enrichment both to the XSLT and adding/removing of nodes in the reference,xml where necessary, to ensure to have a reference.xml, inspired by https://datacite-metadata-schema.readthedocs.io/en/4.5/mappings/force11-software-citation/ and based on https://api.datacite.org/dois/application/vnd.datacite.datacite+xml/10.5281/zenodo.7635478 but still adapted to our metadata and always in the respect of the Datacite metadata vocabulary documentation.

Do you see any other points I should solve there?
