### ISSUE TITLE
Remove old code

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/python-zbMathRest2Oai#33]
[getWithSwagger](https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/blob/0300e11fe5a2e3ff0c06cfd8c99515ea31d5ee89/src/zbmath_rest2oai/getWithSwagger.py) and associated tests can be removed

also associated tests, and the dependency to `    "swagger_client @ git+https://github.com/zbMATHOpen/zbRestApiClient.git"` can be removed. This should significantly improve the code quality ranking

**Comment by Mazztok45** [comment]
I just cleaned many files regarding your suggestion. Do you see any other necessary actions to solve this issue?

**Comment by physikerwelt** [comment]
Thank you
