### ISSUE TITLE
Create a similar test for software

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/python-zbMathRest2Oai#34]
https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/blob/69a6601a0bbcdb48cdfc4d4f15abe17344425139/test/test_plain_xml.py#L11-L35

**Comment by Mazztok45** [comment]
The commit 
https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/commit/ebe5fc3e82f83dd550fc6ac755d2c1bb5a0506f7#diff-2480e7b9524cd0a6cc3b022b9870e5b14e0b1a4281ea82d0b4b96e24e81df0eb
brings the feature to control the similarity between the API and the local file for software metadata.
