### ISSUE TITLE
Remove code and replace in test data

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/python-zbMathRest2Oai#35]
This replacement

https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/blob/ebe5fc3e82f83dd550fc6ac755d2c1bb5a0506f7/test/test_software_metadata.py#L26C1-L34C33

can be avoided, if one replaces the reference data.

**Comment by Mazztok45** [comment]
I updated https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/blob/main/src/zbmath_rest2oai/write_local_test.py

and  https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/blob/main/test/test_software_metadata.py

Does it look better now?

**Comment by physikerwelt** [comment]
Ok, I just wanted you to write 0 to the reference file, but that is also ok. Now the build fails.
