### ISSUE TITLE
Save software and article with prefix

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/python-zbMathRest2Oai#36]
Use

oai:zbmath.org:2615555 

for articles and

oai:swmath.org:2

for software. The last number is the DE number or the swMATH id respectively.

**Comment by Mazztok45** [comment]
I believe my last commit, https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/commit/518cd7ca7ef94387071872ebaccfbad3f7ec6018, fixes this problem by adding the prefix to the identifier.

Do you see any other challenges to close this issue?

**Comment by Mazztok45** [comment]
You are right. I will implement adequate parameters.

**Comment by Mazztok45** [comment]
I implemented https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/commit/4e89e3b98cf009773cb007447d16dda7c0641db7 to add the prefix as a parameter, as you suggested. Do you see other necessary improvements?
