### ISSUE TITLE
Remove requirements.txt

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/python-zbMathRest2Oai#43]
https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/blob/076b4e98be67d0c4cf178c32f269aee114b42e9d/requirements.txt#L2-L31

I think we don't need file. It just increases confusion about the correct way to install the dependencies.

**Comment by Mazztok45** [comment]
Just deleted it with https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/commit/d0d2255d0836516d0d02cba80abf1e47f47de050
