### ISSUE TITLE
Write a test for datacite metadata

### ISSUE THREAD

**Issue by Mazztok45** [MaRDI4NFDI/python-zbMathRest2Oai#44]
Write a test for article metadata testing xslt transform articles metadata to the expected Datacite format.
This work should be equivalent to:
https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/blob/main/test/test_node_names_software_datacite.py

You can almost reuse the same code.

**Comment by Mazztok45** [comment]
AssertionError: 83 not less than or equal to 0 : Found differences between expected and transformed XML

**Comment by Mazztok45** [comment]
The test should run 0 errors. Can you improve it?

**Comment by Shirazos7** [comment]
Yes i will improve it , the plain.xml has been updated and my Test was based on the older version , therefore i will work on the XSLT Code to improve it .

**Comment by Mazztok45** [comment]
I still have issues here, can you work on that?
https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/actions/runs/9043468819/job/24851140209

**Comment by Mazztok45** [comment]
Errors seem coming from the branch API_VERSION_TEST that is not tested on deployment. Should be fixed once we merge it.
