### ISSUE TITLE
Make test to check version of api.zbmath.org

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/python-zbMathRest2Oai#45]
**Describe the issue**
https://api.zbmath.org/openapi.json

it's in info-> version

**Comment by Mazztok45** [comment]
Based on:
https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/blob/main/test/oai_connect_test.py
Develop a similar test to check whenever the REST API version changes.

**Comment by Shirazos7** [comment]
okay , i will start working on it .

**Comment by physikerwelt** [comment]
this is a bit more difficult, as the version information is the openapi specs file https://api.zbmath.org/openapi.json. ChatGPT can help https://chat.openai.com/share/4d0513b3-7410-4d96-ba31-dbeb6c6dae6d

**Comment by Mazztok45** [comment]
This commit from Shiraz fixes this issue:
https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/commit/e6333005e6dc5234eaab2889ae5f7adf6890742c
