### ISSUE TITLE
Manage ZBL ids and related doi of the main object

### ISSUE THREAD

**Issue by Mazztok45** [MaRDI4NFDI/python-zbMathRest2Oai#47]
**Describe the issue**

DOIs and ZBL identifiers of research articles must be displayed into the DataCite vocabulary with the help of the XSLT language.

**Comment by Shirazos7** [comment]
i made two commits regarding to both of them, however i have an idea to discuss it regarding to the zbl identifier . 
anyway i can modify the work if my idea sounds good

**Comment by Shirazos7** [comment]
in this commits you can see my  own modification for xslt and the reference for testing as well 
to enrich the value of our metadata in my own opinion. 
it is only an attempt so it can be always edited
below you can see the commits 
e2ff68b
85378ea

**Comment by Mazztok45** [comment]
<identifier relatedIdentifierType="DOI" relationType="Cites">6383667</identifier>

replaced with 

 <alternateIdentifiers>
      <identifier relatedIdentifierType="DOI" relationType="Cites">6383667</identifier>

The type DOI is still wrong in my opinion. can you fix it?

**Comment by Shirazos7** [comment]
i was aware of it and was only waiting for your feedback about it. 
now you can see the commits for the correction of those details 
fae7975 
c92bf66

**Comment by Mazztok45** [comment]
All right! Many thanks.
