### ISSUE TITLE
Format authors names for the main object and its references 

### ISSUE THREAD

**Issue by Mazztok45** [MaRDI4NFDI/python-zbMathRest2Oai#49]
**Describe the issue**
Once authors are displayed in the new formats for the main article and the references of a zbMATH document, display them in the correct DataCite format with FirstName and FamilyName.

**Comment by Shirazos7** [comment]
i will modify it , once we get the feedback from the team and then we can make it happen ASAP.

**Comment by Mazztok45** [comment]
It has been clarified. 
With the author's code, the first string should be used for Firstname and the second for Lastname. Any other character should be removed with a regex.

**Comment by Shirazos7** [comment]
okay then i will work on it accordingly

**Comment by Shirazos7** [comment]
this issue is fixing the problem , but however it is not like how you recommended it . it is the opposite 

https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/issues/64
