### ISSUE TITLE
Add the rights list to the article XSLT

### ISSUE THREAD

**Issue by Mazztok45** [MaRDI4NFDI/python-zbMathRest2Oai#73]
Add the rights list to the article XSLT like stated in the example below:

https://schema.datacite.org/meta/kernel-4/example/datacite-example-full-v4.xml

**Comment by Shirazos7** [comment]
this commits should fix this issue 

dba6aeb 
03f3cd1 

However i will wate for your feedback to see if there is any changes i should do according to the textual Details 
i focused now on the body and generating it within xslt

**Comment by Mazztok45** [comment]
@physikerwelt, it looks right to me.

**Comment by Shirazos7** [comment]
i adjusted the plain-text according to your feedback
you can see it in the commit below  
b2de956

**Comment by physikerwelt** [comment]
Ok, please merge after fixing the space issue.
