### ISSUE TITLE
devoloping creators , title , description and publicationYear in the xslt for software 

### ISSUE THREAD

**Issue by Shirazos7** [MaRDI4NFDI/python-zbMathRest2Oai#84]
**Issue description**:
we have a new plain.xml which includes some changes of our metadata 
therefore new devolopoment needed to be done in xslt and reference of software metadata
 
 i created a new branch for this work 
i needed to delete all of old work and start a new constrction for our xslt , which leads also to delete the old reference.xml and build from scratch better shape matches with Datacite. 
 
 
**TODOS**: 
identifier , creators , titels , description and publicationYear are going to be excuted in this issue to be solved and devoloped accordingly

**Comment by Shirazos7** [comment]
this commits should fix the issue 

6ef021c 
8745ead

**Comment by Shirazos7** [comment]
@Mazztok45 
@physikerwelt  
i will look forward for your feedback. 
I hope this matches the demand to reshape the creators

**Comment by physikerwelt** [comment]
Looks good, but this is not a pull request. Have you watched the 7min video I shared with you. You can create the pull request from the GitHub web user interface in just a few minutes without any computer skills.

**Comment by Shirazos7** [comment]
i made a pull request and it was successfully merged with no conflicts

**Comment by physikerwelt** [comment]
Almost good. You should have looked at the checks. They told you that you should have removed an unnecessary import. https://app.deepsource.com/gh/MaRDI4NFDI/python-zbMathRest2Oai/run/d9430bc7-3f4c-41c0-9d16-0472cb15a7b7/python/PY-W2000?listindex=0

**Comment by Shirazos7** [comment]
yes i agree with you , i made a new pull request and assigned maxence to approve it with necesssary changes in the python code 
and also new adjustments in xslt .
