### ISSUE TITLE
classification codes and keywords

### ISSUE THREAD

**Issue by Shirazos7** [MaRDI4NFDI/python-zbMathRest2Oai#85]
**Issue description**:
matching our metadata of classifications and keywords with Datacite Schema
 
 
**TODOS**: 

Building  proper templates in xslt to transform the metadata properly

**Comment by Shirazos7** [comment]
the commits here fix the issue 

cac317a 
f099159

**Comment by physikerwelt** [comment]
You already have the branch... https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/compare/main...Xslt_for_software. There is a button to create a pull request... this makes the discussion more convenient
